export const state = {
  token: localStorage.getItem("basha_token") || "",
  enableBackgroundSync: localStorage.getItem("basha_background_sync") === "true",
  lastSyncErrorToastTime: 0,
  networkMode: localStorage.getItem("basha_network_mode") || "online",
  connectionLogs: (() => {
    try {
      return JSON.parse(localStorage.getItem("basha_connection_logs") || "[]");
    } catch (e) {
      return [];
    }
  })(),
  user: null,
  group: null,
  taxRates: [],
  branches: [],
  categories: [],
  menuItems: [],
  suppliers: [],
  inventory: [],
  ingredientYields: [],
  menuItemConsumptions: [],
  stockUsages: [],
  roles: [],
  users: [],
  supplierBills: [],
  supplierOrders: [],
  holidays: [],
  expenses: null,
  operatingExpenses: [],
  performance: [],
  profit: null,
  bills: [],
  summary: null,
  dailyPrepReport: { trend: [], itemSummary: [] },
  prepReportFilter: "all",
  dashboardDate: new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(Date.now() + Number(localStorage.getItem("basha_server_time_offset") || 0))),
  floorStockCounts: {},
  reportPeriod: "month",
  owners: [],
  ownerDraws: [],
  dailyLedger: null,
  orders: [],
  tableOrders: [],
  kots: [],
  loans: [],
  selectedLoanId: null,
  loansScheduleFilter: "all",
  activeView: window.location.pathname.startsWith("/billing") ? "dashboard" : "landing",
  activeCategory: "all",
  masterTab: "menu",
  posSearch: "",
  posMobileTab: "items",
  tablesMobileView: "status",
  customBillingDateTime: "",
  serverTimeOffset: Number(localStorage.getItem("basha_server_time_offset") || 0),
  lastClockSync: localStorage.getItem("basha_last_clock_sync") || "",
  focusQtyId: "",
  focusTableQtyId: "",
  newMenuCategoryId: "",
  editing: {},
  purchaseOrderLines: [],
  billDraftLines: [],
  activeBranchId: localStorage.getItem("basha_branch") || "pondy_main",
  cart: [],
  tableCart: [],
  modal: null,
  activeTableNo: "",
  notifications: [],
  attendanceDate: "",
  attendanceData: [],
  customers: [],
  coupons: [],
  appliedCouponCode: "",
  publicMenu: { branches: [], categories: [], menuItems: [] },
  voiceActive: false,
  voiceFeedback: "",
  voiceError: "",
  customerCart: [],
  customerBranchId: "",
  customerCategory: "all",
  activeServerId: "",
  orderType: "takeaway",
  tableNo: "",
  customerName: "",
  customerPhone: "",
  activeCustomerSearchField: null,
  deliveryAddress: "",
  deliveryFee: 0,
  deliveryTip: 0,
  discountPercent: 0,
  paymentMode: "upi",
  receiptLogo: localStorage.getItem("basha_receipt_logo") || "",
  receiptLogoGrayscale: localStorage.getItem("basha_receipt_logo_grayscale") !== "false",
  receiptAutoCut: localStorage.getItem("basha_receipt_autocut") !== "false",
  splitStandardPrints: localStorage.getItem("splitStandardPrints") !== "false",
  reportShift: "all",
  printerType: localStorage.getItem("printerType") || "none",
  printerStatus: localStorage.getItem("printerStatus") || "disconnected",
  wifiPrinterIp: localStorage.getItem("wifiPrinterIp") || "192.168.1.100",
  paperWidth: localStorage.getItem("paperWidth") || "80mm",
  customerSearch: "",
  selectedCustomerId: null,
  showAddCustForm: false,
  editingCustId: null,
  billsPage: 1,
  billsLimit: 25,
  historyPage: 1,
  historyLimit: 25
};
state.language = localStorage.getItem("basha_language") || "en";

export const rupee = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 0
});

export const tamilLabels = {
  "Active Branch": "செயலில் உள்ள கிளை",
  "Dashboard": "டாஷ்போர்டு",
  "Owner Dashboard": "உரிமையாளர் டாஷ்போர்டு",
  "Tables": "மேசைகள்",
  "Table Service": "மேசை சேவை",
  "POS Billing": "பில்லிங்",
  "Customers": "வாடிக்கையாளர்கள்",
  "Kitchen KOT": "சமையலறை KOT",
  "Inventory": "ஸ்டாக்",
  "Bills": "பில்கள்",
  "Order History": "ஆர்டர் வரலாறு",
  "Order / Bill No": "ஆர்டர் / பில் எண்",
  "Completed At": "முடிந்த நேரம்",
  "Items Ordered": "ஆர்டர் செய்யப்பட்டவை",
  "No completed orders found.": "முடிந்த ஆர்டர்கள் எதுவும் இல்லை.",
  "Search order no or items...": "ஆர்டர் எண் அல்லது பொருளைத் தேடு...",
  "Masters": "மாஸ்டர்",
  "Reports": "அறிக்கைகள்",
  "Refresh": "புதுப்பி",
  "Logout": "வெளியேறு",
  "Language": "மொழி",
  "Stock Register": "ஸ்டாக் பதிவு",
  "Stock Usage": "ஸ்டாக் பயன்பாடு",
  "Purchase Entry": "கொள்முதல் பதிவு",
  "Recent Stock Usage": "சமீபத்திய ஸ்டாக் பயன்பாடு",
  "Item": "பொருள்",
  "Qty": "அளவு",
  "Reorder": "மறு ஆர்டர்",
  "Cost": "செலவு",
  "Supplier": "சப்ளையர்",
  "Stock Item": "ஸ்டாக் பொருள்",
  "Quantity": "அளவு",
  "Unit": "யூனிட்",
  "Total Amount": "மொத்த தொகை",
  "Invoice No": "இன்வாய்ஸ் எண்",
  "Add Purchase": "கொள்முதல் சேர்",
  "Current Stock": "தற்போதைய ஸ்டாக்",
  "Used For": "பயன்பாடு",
  "Notes": "குறிப்புகள்",
  "Save Usage": "பயன்பாட்டை சேமி",
  "Date": "தேதி",
  "Used By": "பதிவு செய்தவர்",
  "Balance": "மீதம்",
  "No stock usage found.": "ஸ்டாக் பயன்பாடு இல்லை.",
  "No inventory items found.": "ஸ்டாக் பொருட்கள் இல்லை.",
  "Cooking": "சமையல்",
  "Prep": "தயாரிப்பு",
  "Wastage": "வீணாகியது",
  "Staff Meal": "பணியாளர் உணவு"
};

export function t(label) {
  return state.language === "ta" ? tamilLabels[label] || label : label;
}

export const logoPath = "/assets/basha-logo.jpeg";
